### ISSUE TITLE
No.

### ISSUE THREAD

**Issue by ThisIsALegitUsername** [lfierro743/Project-EaglercraftY-1.9-version#2]
This is blatantly photoshopped, if you’re going to fake something, do it right. I’m a client developer for eaglercraft (I’m the owner of resent) and I can safely say that you’re never going to be able to port eagler over to 1.9. You likely don’t know sh*t about code/opengl  and a sixth grader would not have the patience or time to do any of this. Stop being a joke and trying to impress your friends, your facade and lies will eventually fall.

**Comment by lfierro743** [comment]
I know code!!
I worked with Html Code
